"""empty message

Revision ID: 00434ca53072
Revises: 009c04dea79f
Create Date: 2019-10-27 17:19:14.186082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00434ca53072'
down_revision = '009c04dea79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_2fa', sa.String(length=11), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'password_2fa')
    # ### end Alembic commands ###
